#include <iostream>
#include <tests.hpp>

int main()
{
    RUN_INT_SLL_NODE_SUITE();
    RUN_INT_SLLIST_SUITE();
    RUN_DLL_NODE_SUITE();
    RUN_DOUBLY_LINKED_LIST_SUITE();
    RUN_CIRCULAR_DOUBLY_LINKED_LIST_SUITE();
    RUN_STACK_TEST_SUITE();
    RUN_QUEUE_TEST_SUITE();
    RUN_DEQUE_TEST_SUITE();
    RUN_RECURSION_TEST_SUITE();
    RUN_BINARY_SEARCH_TREE_TEST_SUITE();
    RUN_BINARY_TREE_NODE_TEST_SUITE();
    RUN_THREADED_BINARY_SEARCH_TREE_TEST_SUITE();
    RUN_GRAPH_MATRIX_TEST_SUITE();
    RUN_DGRAPH_MATRIX_TEST_SUITE();
    RUN_PONDERED_GRAPH_MATRIX_TEST_SUITE();
    RUN_GRAPH_LINKED_LIST_TEST_SUITE();
    RUN_MAZE_TEST_SUITE();
    RUN_DGRAPH_LINKED_LIST_TEST_SUITE();
    RUN_MIN_HEAP_TEST_SUITE();
    RUN_TEST_PRIORITY_QUEUE_MIN();
    std::cout << std::endl;
}
