#ifndef TESTS_H
# define TESTS_H

void RUN_INT_SLL_NODE_SUITE();
void RUN_INT_SLLIST_SUITE();
void RUN_DLL_NODE_SUITE();
void RUN_DOUBLY_LINKED_LIST_SUITE();
void RUN_CIRCULAR_DOUBLY_LINKED_LIST_SUITE();
void RUN_STACK_TEST_SUITE();
void RUN_QUEUE_TEST_SUITE();
void RUN_DEQUE_TEST_SUITE();
void RUN_RECURSION_TEST_SUITE();

#endif