#ifndef TESTS_H
# define TESTS_H

void RUN_INT_SLL_NODE_SUITE();
void RUN_INT_SLLIST_SUITE();
void RUN_DLL_NODE_SUITE();
void RUN_DOUBLY_LINKED_LIST_SUITE();
void RUN_CIRCULAR_DOUBLY_LINKED_LIST_SUITE();
void RUN_STACK_TEST_SUITE();
void RUN_QUEUE_TEST_SUITE();
void RUN_DEQUE_TEST_SUITE();
void RUN_RECURSION_TEST_SUITE();
void RUN_BINARY_SEARCH_TREE_TEST_SUITE();
void RUN_BINARY_TREE_NODE_TEST_SUITE();
void RUN_THREADED_BINARY_SEARCH_TREE_TEST_SUITE();
void RUN_GRAPH_MATRIX_TEST_SUITE();
void RUN_DGRAPH_MATRIX_TEST_SUITE();
void RUN_PONDERED_GRAPH_MATRIX_TEST_SUITE();
void RUN_GRAPH_LINKED_LIST_TEST_SUITE();
void RUN_MAZE_TEST_SUITE();
void RUN_DGRAPH_LINKED_LIST_TEST_SUITE();
void RUN_MIN_HEAP_TEST_SUITE();

#endif